### ISSUE TITLE
Suggestion: simplify your environment scripts

### ISSUE THREAD

**Issue by robertsawko** [BenMql/coral#10]
Ben,

I noticed that in couple of places you keep setting key variables despite having them already in your environment e.g. `CORAL_ROOT` in `prepare_directory.sh`. This happens even if sourcing has occurred before. I suggest you set a default that can be overwritten by the current environment. Check this:

```bash
#!/bin/bash
# filename: example.sh
: "${MY_VARIABLE:=my variable}"
echo ${MY_VARIABLE}
```

and try running with:
```
./example.sh
MY_VARIABLE ./example.sh
```

The reason why I think this useful is that first time users have fewer places to edit. There are some benefits of doing what you're doing so I will keep it as a suggestion.

**Comment by BenMql** [comment]
Robert, 
Thank you, I get your argument against avoiding redundant definition. However your solution goes beyond my knowledge of bash. (I appreciate you taking time to provide an example and I'll educate myself as soon as I can spend a little time brushing up my bash skills.)
From the user perspective, there is also comfort in being able to read and understand scripts (which I believe outweights the cost of having to define some variables twice).
In sum, I would rather keep a status quo on this one.
