### ISSUE TITLE
typos in file describing timeseries

### ISSUE THREAD

**Issue by rhaas80** [BenMql/coral#14]
It may be more consistent to either use `tag` of `kindOfInformation` in both this file and the one describing parameters.

There seems to be a markdown type in the EOF tag given which is given as ``EOF`.

A full definition of a linear variable is called `linear_full_variable` in this file but `linear_variable_full` in Input_file_equations most likely indicating that at least one of them is a typo.

**Comment by BenMql** [comment]
Roland, 
Thank you for your careful review.
`kindOfInformation` is now used in both files; the markdown typo is fixed; `linear_full_variable` has been fixed to `linear_variable_full`.
