### ISSUE TITLE
incorrectly named wiki file Input_usrOutput

### ISSUE THREAD

**Issue by rhaas80** [BenMql/coral#15]
The file Input_usrOutput seems incorrectly named and the wiki page on input files 5_Input_files actually tries to refer to it as Input_file_usrOutput which is consistent with the other input file wiki pages but does not match the actual file name.

Most of the comments in #14 also apply to this file.

**Comment by BenMql** [comment]
Roland, 
The name is fixed, and the link in `5_Input_files` is now valid. The markdown typo, `linear_variable_full` typo, and `kindOfInformation` wording have all been fixed in this file too.
