### ISSUE TITLE
possibly typo incoral_input_1_intro_scalarPDE.ipynb

### ISSUE THREAD

**Issue by rhaas80** [BenMql/coral#16]
The notebook refers to `linear_variable_zero` which it seems to me ought to be `linear_variable_mean`, at least no `_zero` variable has been encountered by my reading of the documtenation so far.

**Comment by BenMql** [comment]
Roland, 
the typo you spotted has been fixed. The description of the different kind of `linear_variable` is now clearer, hopefully.
