### ISSUE TITLE
Expand the statement of need in the documention

### ISSUE THREAD

**Issue by robertsawko** [BenMql/coral#2]
Ben,

Can you also expand the statement of need in the docs [here](https://github.com/BenMql/coral/wiki). The problem the code solves is compactly stated, but the checklist is requesting to include a target audience as well. Note that you mention target audience in the paper.

Also note two minor typos:
 * *eventhough* is spelled separately *even though*,
 * GitHub markdown requires double star to make the text **bold**, which I think was your intention with the acronym.

**Comment by BenMql** [comment]
Robert, 
Thank you for your suggestion, I have expanded the statement of need in the docs. The typos are fixed. 

PS: I'll shortly update the `README` as well
