### ISSUE TITLE
no community guideline

### ISSUE THREAD

**Issue by rhaas80** [BenMql/coral#21]
I seem to be unable to find guidelines for potential contributors. Both technical (make a pull request, create a ticket with a patch, quality expectations, any required formatting style of code) and non-technical (is any transfer of copyright expected?).

related to: https://github.com/openjournals/joss-reviews/issues/2978

**Comment by BenMql** [comment]
@rhaas80 , good point. I have added a `CONTRIBUTING.md` file. With time and as the number of contributors/users increases, the guidelines will evolve.
I leave this issue open for a week, in case you find something missing.
