### ISSUE TITLE
Include a state of field

### ISSUE THREAD

**Issue by robertsawko** [BenMql/coral#3]
Ben,

Can you include in the paper a comparison with other common spectral packages. At the very least I would mention [Nek5000](https://nek5000.mcs.anl.gov/) and Nektar++ [[2]](https://www.sciencedirect.com/science/article/pii/S0010465519304175)[[3]](https://www.nektar.info/).

**Comment by BenMql** [comment]
Hi Robert, 
The paper has been revised and now contains a State of field section.

**Comment by robertsawko** [comment]
Excellent, thanks.
