### ISSUE TITLE
getting error during compilation time

### ISSUE THREAD

**Issue by subhk** [BenMql/coral#31]
Hi Benjamin, 
I cloned the recent version of the code and tried to compile it on the cluster.
I'm getting the below errors- 

/analysis/subhajitkar/data/Results/coral/src/pencils.2decomp/domain_decomposition.f90(18): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [DECOMP_2D]
   use decomp_2d
-------^
/analysis/subhajitkar/data/Results/coral/src/pencils.2decomp/domain_decomposition.f90(19): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [DECOMP_2D_FFT]
   use decomp_2d_fft
-------^
/analysis/subhajitkar/data/Results/coral/src/pencils.2decomp/domain_decomposition.f90(64): error #6404: This name does not have a type, and must have an explicit type.   [ZSTART]
      self%phys_istart = zstart !< copy 2decomp's internal var.
-------------------------^
/analysis/subhajitkar/data/Results/coral/src/pencils.2decomp/domain_decomposition.f90(65): error #6404: This name does not have a type, and must have an explicit type.   [ZEND]
      self%phys_iEnd   = zend   !< copy 2decomp's internal var.
-------------------------^
/analysis/subhajitkar/data/Results/coral/src/pencils.2decomp/domain_decomposition.f90(66): error #6404: This name does not have a type, and must have an explicit type.   [ZSIZE]
      self%phys_iSize  = zsize  !< copy 2decomp's internal var.
-------------------------^
/analysis/subhajitkar/data/Results/coral/src/pencils.2decomp/domain_decomposition.f90(67): error #6404: This name does not have a type, and must have an explicit type.   [IN_CORE_CHEBYSHEV]
      call decomp_2d_fft_init(IN_CORE_CHEBYSHEV)
------------------------------^

Do you know how I am getting these errors?
Any help would be very much appreciated!

Thank you, 
Subhajit

**Comment by BenMql** [comment]
Hi Subhajit, 
most likely there is a problem with the linking of `2decomp`. Did you check that `$DECOMP2D_ROOT` was properly defined? (Just `echo` it.) What's the result of `ls $DECOMP2D_ROOT/include` ? 
If you have installed `fftw` with `--enable-mpi`, try `make clean slabs` to see if you can build the 1D domain decomposition of the code.
Best,
--Ben

**Comment by BenMql** [comment]
Subhajit, 
Assuming that your problem was eventually fixed, I'm closing this issue. Please reopen it if you have new elements. 
Best,
--B.
