### ISSUE TITLE
Consider setting variables in the instructions

### ISSUE THREAD

**Issue by robertsawko** [BenMql/coral#4]
Ben,

Consider setting up the variables in the instructions. It's more compact than writing a sentence on the variable meaning. Novice users will be able to copy-paste and experienced users will interpret it immediately and adjust for their need e.g.

```bash
git clone ...
cd coral
CORAL_ROOT=$(pwd)
# or export CORAL_ROOT=$(PWD)
```
Same for `2decomp&fft` instructions.

**Comment by BenMql** [comment]
Agreed. I have modified [this page](https://github.com/BenMql/coral/wiki/1_Installation) and [this page](https://github.com/BenMql/coral/wiki/Decomp2d_installation) following your suggestion, and the doc does become clearer and easier to read.

**Comment by BenMql** [comment]
A simplified `src/Makefile.inc` is now readily available in the `2decomp_emptyFourierFourier` library. The installation doc is now a little simpler and requires even less actions from the user.
