### ISSUE TITLE
Feedback on compilation instructions

### ISSUE THREAD

**Issue by robertsawko** [BenMql/coral#5]
After fixing [this](https://github.com/BenMql/2decomp_emptyFourierFourier/issues/1) I am progressing with the remaining instructions. I create an environment file, modify accordingly and then the build crashes immediately.

My overall feedback is that some instructions are actually too long. For instance the whole discussion about environment files can be much abbreviated. You could try an enumerated list and simple imperative statements.

You can highlight important variables as sub-bullets in "modify the template" step.

**Comment by BenMql** [comment]
The installation doc used to be a little wordy indeed. Hopefully (i) the crash was due to missing `/` (fixed now) and (ii) the user is now shepherded towards `./etc/set_env_examples/set_env_template.sh` which provides all the necessary informations for defining variables.

**Comment by robertsawko** [comment]
That works. One other thing you could consider in the installation instructions is dropping all the `$` signs and adding a `bash` just after the first triple backtick. This should force Bash colour coding in the wiki. I think GH supports it. Take a look:

```bash
cd ${CORAL_ROOT}
cp ./etc/set_env_examples/set_env_template.sh ./set_env_myMachine.sh
vi set_env_myMachine.sh
chmod +x set_env_myMachine.sh
cd ${CORAL_ROOT}
source ./set_env_myMachine.sh
make clean pencils
```

The difference is not spectacular, but if you have some very inexperienced users they may just do copy/paste and then dollars may confuse them.

**Comment by BenMql** [comment]
Brilliant, most useful hack! I also included some `python` tags where suitable. It does increase the legibility of code snippets. Many thanks
