### ISSUE TITLE
fortran_kinds mod file is missing

### ISSUE THREAD

**Issue by robertsawko** [BenMql/coral#7]
Hello Ben,

I think there are still issues with the make file. When I run `make pencils` I run into this error:

```bash
mpif90 -cpp -O2 -march=native -c /home/rsa/documents/reviews/to_review/miquel2021//coral/src/sparse_tools/sparse_manipulations.f90 -o /home/rsa/documents/reviews/to_review/miquel2021//coral/src/sparse_tools/sparse_manipulations.o -J/home/rsa/documents/reviews/to_review/miquel2021//coral/.mod/ -I/home/rsa/documents/reviews/to_review/miquel2021/2decomp_emptyFourierFourier//include
/home/rsa/documents/reviews/to_review/miquel2021//coral/src/sparse_tools/sparse_manipulations.f90:16:6:

   16 |  use fortran_kinds
      |      1
Fatal Error: Cannot open module file ‘fortran_kinds.mod’ for reading at (1): No such file or directory
compilation terminated.
make: *** [makefile:42: /home/rsa/documents/reviews/to_review/miquel2021//coral/src/sparse_tools/sparse_manipulations.o] Error 1
```
`fortran_kinds.f90` sits in `MISC_DIR` but for some reason the module file is not generated before (is it meant to?). Perhaps something is out of order in the makefile?

**Comment by BenMql** [comment]
Hello Robert, 

This is really puzzling. I cannot reproduce this behaviour, and I cannot wrap my head around it as the `fortran_kinds` module is used by virtually all other modules. I would expect its absence to generate trouble much before compiling `sparse_manipulations.f90`. Perhaps some stray `.o` or `.mod` files still exist from some failed compilation attempts?

Could you `rm` all the `*.o` and `*.mod` file within the coral folder and retry with `make clean pencils` (and send me the full output if it fails)?
(Or simply get a fresh clone of the repository and re-use your `set_env_myMachine.sh` file)
By the way, what is the output of `ls /home/rsa/documents/reviews/to_review/miquel2021//coral/.mod/*`?

The logic behind this makefile is to look for object files, the list of which is given at list 66 of `makefile`. Missing object files trigger their compilation and the creation of their module files, placed in the hidden folder `${CORAL_ROOT}/.mod/`. I have not yet detected a faulty compilation with neither `make 4.10` nor `3.82`, but I have to admit that my knowledge of `make` is vastly empirical.

**Comment by robertsawko** [comment]
Agreed. All fixed on a fresh clone. Must have been an artefact of previous attempts.
