### ISSUE TITLE
Fix minor typos

### ISSUE THREAD

**Issue by robertsawko** [BenMql/coral#9]
Hi Ben,

I forked your wiki page and fixed minor typos in your documentation. It was all written up very well, but there were a few consistent mistakes. For instance time step and time series are still spelled separately anywhere outside of the command line :wink:. I also capitalised "Intel", "Fortran" etc.

Did you know you can edit your wiki locally with any editor? Simply add `.wiki.git` e.g.

```bash
git clone https://github.com/BenMql/coral.wiki.git
```
I typically use VIM with a spellchecker, find and replace and other useful functionalities. You might be using something else, but I think it's useful to know that wiki is also a Git repo.

If you want then to use the wiki I forked and corrected you need to do something like this
```bash
git clone https://github.com/BenMql/coral.wiki.git
cd coral.wiki
git remote add rms https://github.com/robertsawko/coral.wiki.git
git fetch rms
git merge rms/master
```
Your mileage may vary! It's a bit clumsy, but I think GH still does not allow to do a PR for Wikis. What a wonderful world that would have been. :wink:

**Comment by BenMql** [comment]
Hi Robert, 

Thanks for your helpful piece of advice. I do use git and vim to edit the wiki, but I was not aware of the spellchecking capabilities of vim. 

Incidentally, your corrections are much appreciated : thank you so much for going through the wiki yourself! 
I have merged and pushed your corrected version.

**Comment by robertsawko** [comment]
I see, ok so that's quite simple you just use `:set spell`. There are some helpful commands with vim (as you would expect). Take a look [here](https://neovim.io/doc/user/spell.html) or read `:help spell`.
